---

- name: Ensure FPM configuration directories exists
  file:
    path: '{{ inner_item }}'
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - '{{ php__fpm_configuration_directory }}'
  loop_control:
    loop_var: inner_item

- name: List available extensions for FPM
  find:
    paths: '{{ php__extensions_configuration_directory }}'
    file_type: file
  register: _php__installed_extensions_files

- name: List enabled extensions for FPM
  find:
    paths: '{{ php__fpm_include_configuration_directory }}'
    file_type: link
  register: _php__enabled_extensions_files

- name: Parse extensions variables for FPM
  set_fact:
    _php__available_extensions: "{{ _php__installed_extensions_files.files|map(attribute='path')|map('basename')|map('replace', '.ini', '')|list }}"
    _php__enabled_extensions: "{{ _php__enabled_extensions_files.files|map(attribute='path')|map('basename')|map('regex_replace', '^[0-9]+-([^ ]+)\\.ini$', '\\1')|list }}"
    _php__required_extensions: '{{
        php__extensions.keys()|list
        |union(php__fpm_extensions.keys()|list)
        |unique|list
      }}'

- name: Fail is an enabled extension is not available for FPM
  fail:
    msg: "The PHP extension(s) {{ _php__required_extensions|difference(_php__available_extensions)|join(',') }} is(are) not available"
  when: _php__required_extensions|difference(_php__available_extensions)|length > 0

- name: Disable all unwanted php extensions for FPM
  command: 'phpdismod -s fpm {{ inner_item }}'
  with_items: '{{ _php__enabled_extensions|difference(_php__required_extensions)|list }}'
  loop_control:
    loop_var: inner_item
  notify: ['restart-php-fpm']

- name: Enable all wanted php extensions for FPM
  command: 'phpenmod -s fpm {{ inner_item }}'
  with_items: '{{ _php__required_extensions|difference(_php__enabled_extensions)|list }}'
  loop_control:
    loop_var: inner_item
  notify: ['restart-php-fpm']
